github_token: your_github_token_here
deepseek:
  api_key: your_deepseek_api_key_here
  model: deepseek-chat
  api_url: https://api.deepseek.com/v1/chat/completions
  temperature: 0.3
  max_tokens: 1000
api_timeout: 10
api_retries: 3
report:
  output_dir: ai_reports
  max_preview_items:
    releases: 3
    commits: 5
    pull_requests: 5
    issues: 5
logging:
  level: INFO
  file: logs/github-ai-summarizer.log
  max_size: 10
  max_backup: 5
